### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by mmoscosa** [i62navpm/myImageProject#1]
Could you comment or add a template on how the config/config.js file should look please?

**Comment by i62navpm** [comment]
Yes, of course!!
Is basically a config file of Cognito:

```javascript
module.exports = {
  region: '',
  cognito: {
    IdentityPoolId: '',
    UserPoolId: '',
    ClientId: ''
  }
}
```

**Comment by mmoscosa** [comment]
Thank you!

Great project and template btw! much appretiated
